# Generated by Django 6.1.1 on 2026-09-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='legacy_code',
        ),
    ]
